apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx.ingressName" . }}
  labels: 
    {{- include "nginx.labels" . | nindent 4}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nginx.serviceName" . }}
            port:
              number: {{ .Values.service.port }}