apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.serviceName" . }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}