trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: cluster-vars

steps:
- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: aws-eks-authenticator@0
  displayName: AWS EKS Authentication
  inputs:
    clusterName: 'dev-k8s-cluster-us-east-1'
    awsCredentials: 'eks-svc'
    regionName: 'us-east-1'

- task: Bash@3
  displayName: Update KubeConfig
  inputs:
    targetType: 'inline'
    script: 'aws eks update-kubeconfig --region us-east-1 --name $(cluster_name)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'kubectl create -f k8s/aws-test.yaml'