name: First workflow
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'hotfix/**'
      - 'bug/**'
    paths:
      - 'infrastructure/**'
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World"
          echo "Hello World 2!"
      - name: Print Goodbye
        run: echo "Done - bye!"

  # second-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print greeting
  #       run: echo "Hello World"
  #     - name: Print Goodbye
  #       run: echo "Done - bye!"
