name: Test TF Deploy
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'hotfix/**'
      - 'bug/**'
    # paths:
    #   - 'infrastructure/**'
jobs: 
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World"
          echo "Hello World 2!"
      - name: Print Goodbye
        run: echo "Done - bye!"
      - name: Code checkout
        uses: actions/checkout@v3
      - name: List directory
        run: ls -la
      - name: Test Binaries
        run: |
          terraform --version
          aws --version
      - name: Terraform Init and Plan
        run: |
          cd infrastructure/
          terraform init
          terraform plan

  Deploy:
    needs: devDeployment
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye!"
