name: Test TF Deploy
on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'hotfix/**'
      - 'bug/**'
    # paths:
    #   - 'infrastructure/**'
env:
  AWS_REGION: us-east-1
  APP_NAME: k8s
  ENVIRONMENT: dev
jobs: 
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Code checkout
        uses: actions/checkout@v3
      - name: List directory
        run: |
          pwd        
          ls -la -R
      - name: Verify terraform version
        run: terraform --version
      - name: Terraform Init and Plan
        run: |
          cd infrastructure/
          terraform init -var "region=$AWS_REGION" -var "app_name=$APP_NAME" -var "environment=$ENVIRONMENT"
          terraform plan
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye!"
